// Generated by gencpp from file yolov5_ros_msgs/port_serial.msg
// DO NOT EDIT!


#ifndef YOLOV5_ROS_MSGS_MESSAGE_PORT_SERIAL_H
#define YOLOV5_ROS_MSGS_MESSAGE_PORT_SERIAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yolov5_ros_msgs
{
template <class ContainerAllocator>
struct port_serial_
{
  typedef port_serial_<ContainerAllocator> Type;

  port_serial_()
    : id(0)
    , x(0)
    , y(0)
    , distance(0)  {
    }
  port_serial_(const ContainerAllocator& _alloc)
    : id(0)
    , x(0)
    , y(0)
    , distance(0)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;

   typedef int32_t _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::yolov5_ros_msgs::port_serial_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yolov5_ros_msgs::port_serial_<ContainerAllocator> const> ConstPtr;

}; // struct port_serial_

typedef ::yolov5_ros_msgs::port_serial_<std::allocator<void> > port_serial;

typedef boost::shared_ptr< ::yolov5_ros_msgs::port_serial > port_serialPtr;
typedef boost::shared_ptr< ::yolov5_ros_msgs::port_serial const> port_serialConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yolov5_ros_msgs::port_serial_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yolov5_ros_msgs::port_serial_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yolov5_ros_msgs::port_serial_<ContainerAllocator1> & lhs, const ::yolov5_ros_msgs::port_serial_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yolov5_ros_msgs::port_serial_<ContainerAllocator1> & lhs, const ::yolov5_ros_msgs::port_serial_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yolov5_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yolov5_ros_msgs::port_serial_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolov5_ros_msgs::port_serial_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolov5_ros_msgs::port_serial_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolov5_ros_msgs::port_serial_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolov5_ros_msgs::port_serial_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolov5_ros_msgs::port_serial_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yolov5_ros_msgs::port_serial_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2b3c09fcdbc0402971b87d1180f413f1";
  }

  static const char* value(const ::yolov5_ros_msgs::port_serial_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2b3c09fcdbc04029ULL;
  static const uint64_t static_value2 = 0x71b87d1180f413f1ULL;
};

template<class ContainerAllocator>
struct DataType< ::yolov5_ros_msgs::port_serial_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yolov5_ros_msgs/port_serial";
  }

  static const char* value(const ::yolov5_ros_msgs::port_serial_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yolov5_ros_msgs::port_serial_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n"
"int32 x\n"
"int32 y\n"
"int32 distance\n"
;
  }

  static const char* value(const ::yolov5_ros_msgs::port_serial_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yolov5_ros_msgs::port_serial_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct port_serial_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yolov5_ros_msgs::port_serial_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yolov5_ros_msgs::port_serial_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
    s << indent << "distance: ";
    Printer<int32_t>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOLOV5_ROS_MSGS_MESSAGE_PORT_SERIAL_H
