set(_CATKIN_CURRENT_PACKAGE "yolov5_PNP")
set(yolov5_PNP_VERSION "0.0.0")
set(yolov5_PNP_MAINTAINER "yami <yami@todo.todo>")
set(yolov5_PNP_PACKAGE_FORMAT "2")
set(yolov5_PNP_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(yolov5_PNP_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(yolov5_PNP_BUILDTOOL_DEPENDS "catkin")
set(yolov5_PNP_BUILDTOOL_EXPORT_DEPENDS )
set(yolov5_PNP_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(yolov5_PNP_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(yolov5_PNP_TEST_DEPENDS )
set(yolov5_PNP_DOC_DEPENDS )
set(yolov5_PNP_URL_WEBSITE "")
set(yolov5_PNP_URL_BUGTRACKER "")
set(yolov5_PNP_URL_REPOSITORY "")
set(yolov5_PNP_DEPRECATED "")