set(_CATKIN_CURRENT_PACKAGE "yolov5_dection")
set(yolov5_dection_VERSION "0.0.0")
set(yolov5_dection_MAINTAINER "yami <yami@todo.todo>")
set(yolov5_dection_PACKAGE_FORMAT "2")
set(yolov5_dection_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "yolov5_ros_msgs" "sensor_msgs")
set(yolov5_dection_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "yolov5_ros_msgs" "sensor_msgs")
set(yolov5_dection_BUILDTOOL_DEPENDS "catkin")
set(yolov5_dection_BUILDTOOL_EXPORT_DEPENDS )
set(yolov5_dection_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "yolov5_ros_msgs" "sensor_msgs")
set(yolov5_dection_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "yolov5_ros_msgs" "sensor_msgs")
set(yolov5_dection_TEST_DEPENDS )
set(yolov5_dection_DOC_DEPENDS )
set(yolov5_dection_URL_WEBSITE "")
set(yolov5_dection_URL_BUGTRACKER "")
set(yolov5_dection_URL_REPOSITORY "")
set(yolov5_dection_DEPRECATED "")