// Generated by gencpp from file yolov5_ros_msgs/arr.msg
// DO NOT EDIT!


#ifndef YOLOV5_ROS_MSGS_MESSAGE_ARR_H
#define YOLOV5_ROS_MSGS_MESSAGE_ARR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yolov5_ros_msgs
{
template <class ContainerAllocator>
struct arr_
{
  typedef arr_<ContainerAllocator> Type;

  arr_()
    : arr()  {
    }
  arr_(const ContainerAllocator& _alloc)
    : arr(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _arr_type;
  _arr_type arr;





  typedef boost::shared_ptr< ::yolov5_ros_msgs::arr_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yolov5_ros_msgs::arr_<ContainerAllocator> const> ConstPtr;

}; // struct arr_

typedef ::yolov5_ros_msgs::arr_<std::allocator<void> > arr;

typedef boost::shared_ptr< ::yolov5_ros_msgs::arr > arrPtr;
typedef boost::shared_ptr< ::yolov5_ros_msgs::arr const> arrConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yolov5_ros_msgs::arr_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yolov5_ros_msgs::arr_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yolov5_ros_msgs::arr_<ContainerAllocator1> & lhs, const ::yolov5_ros_msgs::arr_<ContainerAllocator2> & rhs)
{
  return lhs.arr == rhs.arr;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yolov5_ros_msgs::arr_<ContainerAllocator1> & lhs, const ::yolov5_ros_msgs::arr_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yolov5_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yolov5_ros_msgs::arr_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolov5_ros_msgs::arr_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolov5_ros_msgs::arr_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolov5_ros_msgs::arr_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolov5_ros_msgs::arr_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolov5_ros_msgs::arr_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yolov5_ros_msgs::arr_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8b419786816700aebca77fec769e86a3";
  }

  static const char* value(const ::yolov5_ros_msgs::arr_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8b419786816700aeULL;
  static const uint64_t static_value2 = 0xbca77fec769e86a3ULL;
};

template<class ContainerAllocator>
struct DataType< ::yolov5_ros_msgs::arr_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yolov5_ros_msgs/arr";
  }

  static const char* value(const ::yolov5_ros_msgs::arr_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yolov5_ros_msgs::arr_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] arr\n"
;
  }

  static const char* value(const ::yolov5_ros_msgs::arr_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yolov5_ros_msgs::arr_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.arr);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct arr_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yolov5_ros_msgs::arr_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yolov5_ros_msgs::arr_<ContainerAllocator>& v)
  {
    s << indent << "arr[]" << std::endl;
    for (size_t i = 0; i < v.arr.size(); ++i)
    {
      s << indent << "  arr[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.arr[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOLOV5_ROS_MSGS_MESSAGE_ARR_H
