# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from yolov5_ros_msgs/arr_rank.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import yolov5_ros_msgs.msg

class arr_rank(genpy.Message):
  _md5sum = "fda0ba7f4327a4a5573e422b6bef24b9"
  _type = "yolov5_ros_msgs/arr_rank"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """arr[] arrs
int32[] rank
================================================================================
MSG: yolov5_ros_msgs/arr
int32[] arr"""
  __slots__ = ['arrs','rank']
  _slot_types = ['yolov5_ros_msgs/arr[]','int32[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       arrs,rank

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(arr_rank, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.arrs is None:
        self.arrs = []
      if self.rank is None:
        self.rank = []
    else:
      self.arrs = []
      self.rank = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.arrs)
      buff.write(_struct_I.pack(length))
      for val1 in self.arrs:
        length = len(val1.arr)
        buff.write(_struct_I.pack(length))
        pattern = '<%si'%length
        buff.write(struct.Struct(pattern).pack(*val1.arr))
      length = len(self.rank)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.Struct(pattern).pack(*self.rank))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.arrs is None:
        self.arrs = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.arrs = []
      for i in range(0, length):
        val1 = yolov5_ros_msgs.msg.arr()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%si'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.arr = s.unpack(str[start:end])
        self.arrs.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.rank = s.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.arrs)
      buff.write(_struct_I.pack(length))
      for val1 in self.arrs:
        length = len(val1.arr)
        buff.write(_struct_I.pack(length))
        pattern = '<%si'%length
        buff.write(val1.arr.tostring())
      length = len(self.rank)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.rank.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.arrs is None:
        self.arrs = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.arrs = []
      for i in range(0, length):
        val1 = yolov5_ros_msgs.msg.arr()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%si'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.arr = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
        self.arrs.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.rank = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
